### ISSUE TITLE
1.6 support

### ISSUE THREAD

**Issue by Razikus** [CycloneDX/cyclonedx-go#140]
Is there any ETA when 1.6 spec will be compatible with this library?

**Comment by nscuro** [comment]
No ETA. I am currently swamped with other responsibilities :(

Community contributions would help in getting this done sooner.

**Comment by Razikus** [comment]
thats sad, its official library for cyclonedx :(

**Comment by nscuro** [comment]
@Razikus Please stop commenting "bump". It does not help.

**Comment by Razikus** [comment]
> @Razikus Please stop commenting "bump". It does not help.

Sorry

**Comment by mcombuechen** [comment]
Hey @nscuro 

we (some of the folks at Snyk) would love to help out with this. Since this should probably happen in smaller chunks, we wonder how we can best contribute without stepping on other contributors toes (e.g. there's already a good looking PR for the CBOM model).

Suggestion would be to create a `spec/1.6` (name TBD) branch and start merging small PRs into it. We should probably also fan out into smaller GitHub issues with the `spec/1.6` for a comprehensive list of all the required changes. We're happy to help with that, too.

What do you think?

**Comment by mcombuechen** [comment]
Thanks @nscuro 

> But will require a bit of research.

We already did a bit of research based on diffs between the 1.5 and 1.6 JSON schemas; I had not been aware of the spec milestones, will look into those as well. I can make a start by creating _some_ issues, if we happen to miss anything please shout! 😄

**Comment by mcombuechen** [comment]
Hey @nscuro, I believe we're at a point where all the new schema additions have been added. What do you think is still outstanding to get `spec/1.6` merged?
